Name: elian-blog-api
Host: 0.0.0.0
Port: 8080
Mode: dev
MaxBytes: 52428800

Database:
  Host: 127.0.0.1
  Port: 3306
  Username: root
  Password: root
  DBName: elian_blog
  Charset: utf8mb4
  MaxIdleConns: 10
  MaxOpenConns: 100

Redis:
  Host: 127.0.0.1
  Port: 6379
  Password: ""
  DB: 0

JWT:
  Secret: "elian-blog-jwt-secret-key-change-in-production"
  ExpireHours: 72

AppLog:
  Level: debug

Upload:
  Path: "./uploads"
  MaxSize: 10485760
  BaseURL: "http://localhost:8080"